//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taki.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class purview
    {
        public string PurviewID { get; set; }
        public string PurviewName { get; set; }
        public string PurviewUrl { get; set; }
        public string PurviewIcon { get; set; }
        public string PPurviewID { get; set; }
        public long SequenceNO { get; set; }
        public string PurviewType { get; set; }
        public int Status { get; set; }
    }
}
