//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taki.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysmenu
    {
        public string MenuID { get; set; }
        public string MenuName { get; set; }
        public string MenuUrl { get; set; }
        public string MenuIcon { get; set; }
        public string MenuParentID { get; set; }
        public string MenuOrder { get; set; }
        public bool IsVisible { get; set; }
    }
}
