//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taki.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string UserID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Nickname { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public long Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Status { get; set; }
        public bool IsAdministrator { get; set; }
    }
}
